/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FizzBuzz;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello! Running FizzBuzzBang on 1...100");
        FizzBuzz fizzbuzz = new FizzBuzz();
        for(int iii=1; iii<100; iii++){
            System.out.printf("%d -> %s %n",iii,fizzbuzz.toString(iii));
        }
    }
}
